config/routes.rb
Rails.application.routes.draw do
  resources :memos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources:posts do
    resources :comments,only:[:create,:destroy]
  end

  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body,presence: true
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    #@post.comments
    validates :title,presence: true, length:{minimum:3,message:'Too short to post!'}
    validates :body,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post=Post.find(params[:post_id])
    @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post=Post.find(params[:post_id])
    @comment=@post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url, notice: 'Memo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:title, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts=Post.all.order(created_at:'desc')
    end

    def show
        @post=Post.find(params[:id])
    end

    def new
      @post=Post.new
    end

    def create
      #render plain:params[:post].inspect
      #@post=Post.new(params[:post])
      @post=Post.new(post_params)
        if @post.save
          redirect_to posts_path
        else
          #render plain: @post.errors.inspect
          render 'new'
        end
    end

    def edit
      @post=Post.find(params[:id])
    end

    def update
      @post=Post.find(params[:id])
      if @post.update(post_params)
        redirect_to post_path
      else
        render 'edit'
      end
    end

    def destroy
      @post=Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
    end

    private
      def post_params
        params.require(:post).permit(:title, :body)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h1><%= link_to image_tag('logo.png', class:'logo'), root_path %></h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/memos/_form.html.erb
<%= form_with(model: memo, local: true) do |form| %>
  <% if memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :memo_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :memo_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.title %></td>
        <td><%= memo.body %></td>
        <td><%= link_to 'Show', memo %></td>
        <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
        <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memo', new_memo_path %>

app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Back', memos_path %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @memo.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @memo.body %>
</p>

<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>

app/views/posts/_form.html.erb
<%=form_for @post do |f| %>
<p>
  <%=f.text_field:title,placeholder:'enter title'%>
    <%if @post.errors.messages[:title].any?%>
    <span class="error"><%=@post.errors.messages[:title][0]%></span>
  <%end%>
</p>
<p>
  <%=f.text_area:body,placeholder:'enter body text'%>
    <%if @post.errors.messages[:body].any?%>
    <span class="error"><%=@post.errors.messages[:body][0]%></span>
  <%end%>
</p>
<p>
  <%=f.submit%>
</p>
<%end%>

app/views/posts/edit.html.erb
<h2>
Edit Post
</h2>

<%=render 'form'%>

app/views/posts/index.html.erb
<h2>
  <%=link_to 'Add New',new_post_path,class:'header-menu'%>
  My Posts
</h2>
<ul>
<% @posts.each do |post| %>
<li>
  <%= link_to post.title, post_path(post) %>
  <%=link_to '[Edit]',edit_post_path(post),class:'command'%>
  <%=link_to '[x]',
  post_path(post),
  method: :delete ,
  class:'command',
  data:{confirm:'Sure?'} %>
</li>
<% end %>
</ul>

app/views/posts/new.html.erb
<h2>
Add New Post
</h2>

<%=render 'form'%>

app/views/posts/show.html.erb
<h2>
  <%=@post.title%>
</h2>
<p>
<%=simple_format @post.body%>
</p>
<h3>Comments</h3>

<% if @post.comments.any?%>
<ul>
  <%@post.comments.each do|comment|%>
  <li>
    <%=comment.body%>
    <%=link_to '[x]',
      post_comment_path(@post,comment),
      method: :delete ,
      class:'command',
      data:{confirm:'Sure?'} %>
  </li>
  <%end%>
</ul>
<%end%>
<%=form_for([@post,@post.comments.build]) do |f| %>
<p>
  <%=f.text_field :body%>
</p>
<p>
  <%=f.submit%>
</p>
<%end%>